[package]
name = "torrent-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
eyre = "0.6"
hex = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"